In [109]:
###Carga de Librerias
##pandas Visualizacion de datos {modelo excel}
##numpy Analisis matematico y cientifico de datos {arrays}

In [110]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

#Carga del DataSet

In [111]:
df=pd.read_csv("C:/Users/PC/Desktop/Tesis/Practicum4_SistemasInteligentes_UTPL/DataSet/Dataset.csv",nrows=10000,encoding="ISO-8859-1")

In [112]:
##Visualizacion de los datos (5 primeros datos)

In [113]:
df.head()

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,male,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,female,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,male,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,female,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,male,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN

In [114]:
#Contar los registros totales del dataset (Cuento cualquier columna del dataset)

In [115]:
df.id.count()

1085

In [116]:
##Visualizacion de todos los datos del dataset
##Ya sabemos el numero de registros que posee el dataset

In [117]:
df.head(1085)

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,male,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,female,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,male,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,female,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,male,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,1081,2,2/25/2020,Innsbruck,Austria,NaN,24.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1081,1082,1,2/24/2020,Afghanistan,Afghanistan,NaN,35.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1082,1083,1,2/26/2020,Algeria,Algeria,male,NaN,NaN,NaN,NaN,2/17/2020,0,0,0,0,NaN
1083,1084,1,2/25/2020,Croatia,Croatia,male,NaN,NaN,NaN,2/19/2020,2/21/2020,0,0,0,0,NaN
1084,1085,1,2/25/2020,Bern,Switzerland,male,70.0,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,0,0,NaN

In [118]:
##Filtrado de datos 1
##Por logica deducimos que genero (gender) y edad (age) teniendo datos desconocidos NA (NaN) no aportan mucho a nuestro 
##analisis de datos por lo que procedemos a actualizar nuestro dataset sin estos valores.
##Gender = NA
##Age = NA

In [119]:
df_New=df[(df["gender"].notnull())&(df["age"].notnull())]

In [120]:
##Nuestro nuevo dataframe tiene 825 registros y 16 columnas

In [121]:
df_New.head(825)

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,male,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,female,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,male,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,female,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,male,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,1028,32,2/28/2020,Andalusia,Spain,male,58.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1029,1030,34,2/28/2020,Zaragoza,Spain,female,27.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1030,1031,1,1/31/2020,Jonkoping,Sweden,female,25.0,1/27/2020,NaN,NaN,1/24/2020,1,0,0,0,cough
1052,1053,1,2/21/2020,Lebanon,Lebanon,female,45.0,NaN,NaN,NaN,2/20/2020,0,0,0,0,NaN
1084,1085,1,2/25/2020,Bern,Switzerland,male,70.0,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,0,0,NaN

In [122]:
##Filtrado de datos 2
##Los valores de gender: male y female no son manipulables, por lo que procedemos a convertirlos en valores
##que se puedan manejar 
## 0 = femenino
## 1 = masculino

In [123]:
df_New['gender'].replace(['female','male'],[0,1],inplace=True)

In [124]:
df_New.head(825)

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,1,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,0,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,1,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,0,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,1,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,1028,32,2/28/2020,Andalusia,Spain,1,58.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1029,1030,34,2/28/2020,Zaragoza,Spain,0,27.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1030,1031,1,1/31/2020,Jonkoping,Sweden,0,25.0,1/27/2020,NaN,NaN,1/24/2020,1,0,0,0,cough
1052,1053,1,2/21/2020,Lebanon,Lebanon,0,45.0,NaN,NaN,NaN,2/20/2020,0,0,0,0,NaN
1084,1085,1,2/25/2020,Bern,Switzerland,1,70.0,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,0,0,NaN

In [125]:
##Un tipo ‘O’ solo significa “objeto” que en el mundo de Pandas es una secuencia de caracteres (texto).
##Validando el tipo de dato de la columna Sintoma

In [1]:
df_New['symptom'].dtype

NameError: name 'df_New' is not defined

In [127]:
df_New.dtypes

id                   int64
case_in_country      int64
reporting date      object
location            object
country             object
gender               int64
age                float64
symptom_onset       object
hosp_visit_date     object
exposure_start      object
exposure_end        object
visiting Wuhan       int64
from Wuhan           int64
death                int64
recovered            int64
symptom             object
dtype: object

In [128]:
##Filtrado de datos 3
###Agregar 8 columnas:
##1{fever,high fever,mild fever}
##2{cough,coughing,cough with sputum}
##3{vomiting,nausea,Fatigue}
##4{difficult in breathing,respiratory distress,shortness of breath,difficulty breathing}
##5{Headache,heavy head}
##6{sore throat,throat pain,throat discomfort,itchy throat}
##7{chill,chills,cold}
##8{otherSymptom}
##Estas columnas se llenaran con ceros y unos (1 y 0)
##1 Significa que presenta el sintoma
##0 Significa que no presenta el sintoma

In [129]:
#Agregar columna 1

In [130]:
df_New["Fever, Mild_Fever, High_Fever"]=((df_New["symptom"].str.contains('fever', regex=False))*1)

In [131]:
#Visualizacion Fila desde la 300 a la 310
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1

In [82]:
##Ver el tamano de nuestro dataframe

In [83]:
df_New.shape

(825, 17)

In [84]:
#Agregar columna 2

In [85]:
df_New["Cough, Coughing, cough_with_sputum"]=((df_New["symptom"].str.contains('cough', regex=False))*1)

In [86]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0

In [87]:
#Agregar columna 3

In [88]:
df_New["Vomiting, Nausea, Fatigue"]=((df_New["symptom"].str.contains('vomiting|nausea|fatigue', regex=True))*1)

In [89]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0,1
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0,0

In [90]:
##Agregar columna 4

In [91]:
df_New["difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing"]=(df_New["symptom"].str.contains('breath|distress', regex=True))*1

In [92]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0,0,1
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0,1,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1,0,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0,0,0

In [93]:
##Agregar columna 5

In [94]:
df_New["Headache, heavy_head"]=((df_New["symptom"].str.contains('head', regex=False))*1)

In [95]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,0,1,0,difficulty breathing,0,0,0,1,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,0,0,fever/ cough/ malaise,1,1,0,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,0,0,fever,1,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,0,0,fatigue/ malaise/ headache,0,0,1,0,1
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,...,0,0,0,0,fever/ sore throat/ malaise,1,0,0,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,...,0,0,0,0,sore throat/ cough/ fever,1,1,0,0,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,...,0,0,0,0,fever/ cough,1,1,0,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,...,0,0,0,0,fever/ nasal discharge/ headache,1,0,0,0,1
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,...,0,0,0,0,fever,1,0,0,0,0

In [96]:
##Agregar columna 6

In [97]:
df_New["sore_throat, throat_pain, throat_discomfort, itchy_throat"]=((df_New["symptom"].str.contains('throat', regex=False))*1)

In [98]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,1,0,difficulty breathing,0,0,0,1,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,0,fever/ cough/ malaise,1,1,0,0,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,0,fever,1,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,0,fatigue/ malaise/ headache,0,0,1,0,1,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,...,0,0,0,fever/ sore throat/ malaise,1,0,0,0,0,1
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,...,0,0,0,sore throat/ cough/ fever,1,1,0,0,0,1
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,...,0,0,0,fever/ cough,1,1,0,0,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,...,0,0,0,fever/ nasal discharge/ headache,1,0,0,0,1,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,...,0,0,0,fever,1,0,0,0,0,0

In [99]:
##Agregar columna 7

In [100]:
df_New["chill, chills, cold"]=((df_New["symptom"].str.contains('chill|cold', regex=True))*1)

In [101]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,1,0,difficulty breathing,0,0,0,1,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,fever/ cough/ malaise,1,1,0,0,0,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,fever,1,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,fatigue/ malaise/ headache,0,0,1,0,1,0,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,...,0,0,fever/ sore throat/ malaise,1,0,0,0,0,1,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,...,0,0,sore throat/ cough/ fever,1,1,0,0,0,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,...,0,0,fever/ cough,1,1,0,0,0,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,...,0,0,fever/ nasal discharge/ headache,1,0,0,0,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,...,0,0,fever,1,0,0,0,0,0,0

In [102]:
##Agregar columna 8

In [103]:
df_New["Other Symptom"]=((df_New["symptom"].str.contains('joint|runny|diarrhea|abdominal|pneumonia|loss|malaise|sputum|muscle|breathlessness|dyspnea|loss|nasal|mild|sneeze|chest|thirst|flu|cramps|aching|body|aches|reflux|physical|tired|myalgias', regex=True))*1)

In [104]:
df_New[300:305]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold",Other Symptom
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,difficulty breathing,0,0,0,1,0,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,fever/ cough/ malaise,1,1,0,0,0,0,0,1
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,fever,1,0,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,fatigue/ malaise/ headache,0,0,1,0,1,0,0,1

In [105]:
##Filtrado de datos 3
##En Base a que queremos pronosticar 
##Eliminar la columna muerte (death) y la columna Sintoma (symptom)

In [106]:
df_New.drop(['death', 'symptom'], axis=1, inplace=True)

In [107]:
df_New[300:305]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,from Wuhan,recovered,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold",Other Symptom
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,0,0,0,0,1,0,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,1,1,0,0,0,0,0,1
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,1,0,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,0,0,1,0,1,0,0,1

In [ ]:
##Filtrado de datos 4
##En la columna Symptom hay valores con NA
##Estos valores NA quiere decir que es asintomatico (No presento ningun sintoma de las ocho columnas)
##Por lo que se procede a crear una nueva columna (Asintomatico)con estos valores