In [30]:
###Carga de Librerias
##pandas Visualizacion de datos {modelo excel}
##numpy Analisis matematico y cientifico de datos {arrays}

In [31]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

#Carga del DataSet

In [32]:
df=pd.read_csv("C:/Users/PC/Desktop/Tesis/Practicum4_SistemasInteligentes_UTPL/DataSet/Dataset.csv",nrows=10000,encoding="ISO-8859-1")

In [33]:
##Visualizacion de los datos (5 primeros datos)

In [34]:
df.head()

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,male,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,female,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,male,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,female,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,male,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN

In [35]:
#Contar los registros totales del dataset (Cuento cualquier columna del dataset)

In [36]:
df.id.count()

1085

In [37]:
##Visualizacion de todos los datos del dataset
##Ya sabemos el numero de registros que posee el dataset

In [38]:
df.head(1085)

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,male,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,female,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,male,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,female,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,male,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,1081,2,2/25/2020,Innsbruck,Austria,NaN,24.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1081,1082,1,2/24/2020,Afghanistan,Afghanistan,NaN,35.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1082,1083,1,2/26/2020,Algeria,Algeria,male,NaN,NaN,NaN,NaN,2/17/2020,0,0,0,0,NaN
1083,1084,1,2/25/2020,Croatia,Croatia,male,NaN,NaN,NaN,2/19/2020,2/21/2020,0,0,0,0,NaN
1084,1085,1,2/25/2020,Bern,Switzerland,male,70.0,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,0,0,NaN

In [39]:
##Filtrado de datos 1
##Por logica deducimos que genero (gender) y edad (age) teniendo datos desconocidos NA (NaN) no aportan mucho a nuestro 
##analisis de datos por lo que procedemos a actualizar nuestro dataset sin estos valores.
##Gender = NA
##Age = NA

In [40]:
df_New=df[(df["gender"].notnull())&(df["age"].notnull())]

In [41]:
##Nuestro nuevo dataframe tiene 825 registros y 16 columnas

In [42]:
df_New.head(825)

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,male,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,female,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,male,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,female,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,male,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,1028,32,2/28/2020,Andalusia,Spain,male,58.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1029,1030,34,2/28/2020,Zaragoza,Spain,female,27.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1030,1031,1,1/31/2020,Jonkoping,Sweden,female,25.0,1/27/2020,NaN,NaN,1/24/2020,1,0,0,0,cough
1052,1053,1,2/21/2020,Lebanon,Lebanon,female,45.0,NaN,NaN,NaN,2/20/2020,0,0,0,0,NaN
1084,1085,1,2/25/2020,Bern,Switzerland,male,70.0,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,0,0,NaN

In [43]:
##Filtrado de datos 2
##Los valores de gender: male y female no son manipulables, por lo que procedemos a convertirlos en valores
##que se puedan manejar 
## 0 = femenino
## 1 = masculino

In [44]:
df_New['gender'].replace(['female','male'],[0,1],inplace=True)

In [45]:
df_New.head(825)

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom
0,1,0,1/20/2020,Shenzhen Guangdong,China,1,66.0,1/3/20,1/11/20,12/29/2019,1/4/20,1,0,0,0,NaN
1,2,0,1/20/2020,Shanghai,China,0,56.0,1/15/2020,1/15/2020,NaN,1/12/20,0,1,0,0,NaN
2,3,0,1/21/2020,Zhejiang,China,1,46.0,1/4/20,1/17/2020,NaN,1/3/20,0,1,0,0,NaN
3,4,0,1/21/2020,Tianjin,China,0,60.0,NaN,1/19/2020,NaN,NaN,1,0,0,0,NaN
4,5,0,1/21/2020,Tianjin,China,1,58.0,NaN,1/14/2020,NaN,NaN,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,1028,32,2/28/2020,Andalusia,Spain,1,58.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1029,1030,34,2/28/2020,Zaragoza,Spain,0,27.0,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1030,1031,1,1/31/2020,Jonkoping,Sweden,0,25.0,1/27/2020,NaN,NaN,1/24/2020,1,0,0,0,cough
1052,1053,1,2/21/2020,Lebanon,Lebanon,0,45.0,NaN,NaN,NaN,2/20/2020,0,0,0,0,NaN
1084,1085,1,2/25/2020,Bern,Switzerland,1,70.0,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,0,0,NaN

In [46]:
##Un tipo ‘O’ solo significa “objeto” que en el mundo de Pandas es una secuencia de caracteres (texto).
##Validando el tipo de dato de la columna Sintoma

In [47]:
df_New['symptom'].dtype

dtype('O')

In [48]:
df_New.dtypes

id                   int64
case_in_country      int64
reporting date      object
location            object
country             object
gender               int64
age                float64
symptom_onset       object
hosp_visit_date     object
exposure_start      object
exposure_end        object
visiting Wuhan       int64
from Wuhan           int64
death                int64
recovered            int64
symptom             object
dtype: object

In [29]:
##Filtrado de datos 3
###Agregar 8 columnas:
##1{fever,high fever,mild fever}
##2{cough,coughing,cough with sputum}
##3{vomiting,nausea,Fatigue}
##4{difficult in breathing,respiratory distress,shortness of breath,difficulty breathing}
##5{Headache,heavy head}
##6{sore throat,throat pain,throat discomfort,itchy throat}
##7{chill,chills,cold}
##8{otherSymptom}
##Estas columnas se llenaran con ceros y unos (1 y 0)
##1 Significa que presenta el sintoma
##0 Significa que no presenta el sintoma

In [129]:
#Agregar columna 1

In [60]:
df_New["Fever, Mild_Fever, High_Fever"]=((df_New["symptom"].str.contains('fever',na=False,regex=False))*1)

In [61]:
#Visualizacion Fila desde la 300 a la 310
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0,1
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0,0

In [62]:
##Ver el tamano de nuestro dataframe

In [63]:
df_New.shape

(825, 19)

In [64]:
#Agregar columna 2

In [65]:
df_New["Cough, Coughing, cough_with_sputum"]=((df_New["symptom"].str.contains('cough',na=False,regex=False))*1)

In [66]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0,1
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0,0

In [67]:
#Agregar columna 3

In [68]:
df_New["Vomiting, Nausea, Fatigue"]=((df_New["symptom"].str.contains('vomiting|nausea|fatigue',na=False,regex=True))*1)

In [69]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0,1
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0,0

In [73]:
##Agregar columna 4

In [74]:
df_New["difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing"]=(df_New["symptom"].str.contains('breath|distress',na=False,regex=True))*1

In [75]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,NaN,0,0,1,0,difficulty breathing,0,0,0,1
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,NaN,0,0,0,0,fever/ cough/ malaise,1,1,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,NaN,0,0,0,0,NaN,0,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,NaN,0,0,0,0,fever,1,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,NaN,0,0,0,0,fatigue/ malaise/ headache,0,0,1,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,NaN,0,0,0,0,fever/ sore throat/ malaise,1,0,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,NaN,0,0,0,0,sore throat/ cough/ fever,1,1,0,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,NaN,0,0,0,0,fever/ cough,1,1,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,NaN,0,0,0,0,fever/ nasal discharge/ headache,1,0,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,NaN,0,0,0,0,fever,1,0,0,0

In [76]:
##Agregar columna 5

In [77]:
df_New["Headache, heavy_head"]=((df_New["symptom"].str.contains('head',na=False,regex=False))*1)

In [78]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,visiting Wuhan,from Wuhan,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,0,1,0,difficulty breathing,0,0,0,1,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,0,0,fever/ cough/ malaise,1,1,0,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,0,0,NaN,0,0,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,0,0,fever,1,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,0,0,fatigue/ malaise/ headache,0,0,1,0,1
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,...,0,0,0,0,fever/ sore throat/ malaise,1,0,0,0,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,...,0,0,0,0,sore throat/ cough/ fever,1,1,0,0,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,...,0,0,0,0,fever/ cough,1,1,0,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,...,0,0,0,0,fever/ nasal discharge/ headache,1,0,0,0,1
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,...,0,0,0,0,fever,1,0,0,0,0

In [85]:
##Agregar columna 6

In [86]:
df_New["sore_throat, throat_pain, throat_discomfort, itchy_throat"]=((df_New["symptom"].str.contains('throat',na=False,regex=False))*1)

In [87]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,1,0,difficulty breathing,0,0,0,1,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,fever/ cough/ malaise,1,1,0,0,0,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,NaN,0,0,0,0,0,0,NaN
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,fever,1,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,fatigue/ malaise/ headache,0,0,1,0,1,0,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,...,0,0,fever/ sore throat/ malaise,1,0,0,0,0,1,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,...,0,0,sore throat/ cough/ fever,1,1,0,0,0,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,...,0,0,fever/ cough,1,1,0,0,0,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,...,0,0,fever/ nasal discharge/ headache,1,0,0,0,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,...,0,0,fever,1,0,0,0,0,0,0

In [88]:
##Agregar columna 7

In [89]:
df_New["chill, chills, cold"]=((df_New["symptom"].str.contains('chill|cold',na=False, regex=True))*1)

In [90]:
df_New[300:310]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,death,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold"
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,1,0,difficulty breathing,0,0,0,1,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,0,fever/ cough/ malaise,1,1,0,0,0,0,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,NaN,0,0,0,0,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,0,fever,1,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,fatigue/ malaise/ headache,0,0,1,0,1,0,0
339,340,104,2/22/2020,Hokkaido,Japan,0,15.0,2/6/20,2/7/20,NaN,...,0,0,fever/ sore throat/ malaise,1,0,0,0,0,1,0
340,341,105,2/22/2020,Hokkaido,Japan,0,55.0,2/13/2020,2/15/2020,NaN,...,0,0,sore throat/ cough/ fever,1,1,0,0,0,1,0
341,342,106,2/22/2020,Tokyo,Japan,1,65.0,2/12/20,NaN,NaN,...,0,0,fever/ cough,1,1,0,0,0,0,0
342,343,107,2/22/2020,Nagoya City,Japan,0,65.0,2/19/2020,2/21/2020,NaN,...,0,0,fever/ nasal discharge/ headache,1,0,0,0,1,0,0
343,344,108,2/22/2020,Nagoya City,Japan,0,46.0,2/20/2020,2/21/2020,NaN,...,0,0,fever,1,0,0,0,0,0,0

In [91]:
##Agregar columna 8

In [92]:
df_New["Other Symptom"]=((df_New["symptom"].str.contains('joint|runny|diarrhea|abdominal|pneumonia|loss|malaise|sputum|muscle|breathlessness|dyspnea|loss|nasal|mild|sneeze|chest|thirst|flu|cramps|aching|body|aches|reflux|physical|tired|myalgias',na=False,regex=True))*1)

In [94]:
df_New[300:305]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,recovered,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold",Other Symptom
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,difficulty breathing,0,0,0,1,0,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,fever/ cough/ malaise,1,1,0,0,0,0,0,1
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,NaN,0,0,0,0,0,0,0,0
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,fever,1,0,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,fatigue/ malaise/ headache,0,0,1,0,1,0,0,1

In [95]:
##Filtrado de datos 3
##En la columna Symptom hay valores con NA (NaN) (Not an number)
##Estos valores NA quiere decir que es asintomatico (No presento ningun sintoma de las ocho columnas indicadas)
##Por lo que se procede a crear una nueva columna (Asintomatico)con estos valores

In [96]:
df_New["Asintomatico"]=((df_New["symptom"].str.contains('SinSintomas',na=True,regex=True))*1)

In [98]:
df_New[200:210]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,symptom,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold",Other Symptom,Asintomatico
226,227,30,2/27/2020,Nantes,France,0,58.0,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,0,0,1
227,228,31,2/27/2020,Montpellier,France,1,31.0,NaN,2/27/2020,NaN,...,NaN,0,0,0,0,0,0,0,0,1
229,230,33,2/27/2020,Brest,France,1,72.0,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,0,0,1
231,232,35,2/27/2020,Lyon,France,1,50.0,NaN,2/26/2020,NaN,...,NaN,0,0,0,0,0,0,0,0,1
233,234,37,2/27/2020,Annecy,France,0,35.0,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,0,0,1
235,236,39,2/28/2020,Nice,France,0,23.0,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,0,0,1
236,237,1,1/15/2020,Kanagawa,Japan,1,35.0,1/3/20,1/6/20,NaN,...,fever,1,0,0,0,0,0,0,0,0
237,238,2,1/24/2020,Tokyo,Japan,1,45.0,1/14/2020,1/15/2020,NaN,...,NaN,0,0,0,0,0,0,0,0,1
238,239,3,1/25/2020,Tokyo,Japan,0,35.0,1/21/2020,1/23/2020,NaN,...,NaN,0,0,0,0,0,0,0,0,1
239,240,4,1/26/2020,Aichi Prefecture,Japan,1,45.0,1/23/2020,1/24/2020,NaN,...,NaN,0,0,0,0,0,0,0,0,1

In [99]:
##Filtrado de datos 4
##El caso de estudio es acerca de la prediccion de enfermos con Covid
##Por lo que se procede a eliminar la columna muerte (death)
##Adicional se elimina la columna Simtomas (symptom) por que ya fueron desglosadas

In [100]:
df_New.drop(['death', 'symptom'], axis=1, inplace=True)

In [101]:
df_New[300:305]

,id,case_in_country,reporting date,location,country,gender,age,symptom_onset,hosp_visit_date,exposure_start,...,recovered,"Fever, Mild_Fever, High_Fever","Cough, Coughing, cough_with_sputum","Vomiting, Nausea, Fatigue","difficult_in_breathing, respiratory_distress, shortness_of_breath, difficulty_breathing","Headache, heavy_head","sore_throat, throat_pain, throat_discomfort, itchy_throat","chill, chills, cold",Other Symptom,Asintomatico
334,335,99,2/22/2020,Hokkaido,Japan,1,85.0,2/3/20,2/3/20,NaN,...,0,0,0,0,1,0,0,0,0,0
335,336,100,2/22/2020,Hokkaido,Japan,1,75.0,2/16/2020,2/20/2020,NaN,...,0,1,1,0,0,0,0,0,1,0
336,337,101,2/22/2020,Hokkaido,Japan,0,55.0,2/17/2020,2/19/2020,NaN,...,0,0,0,0,0,0,0,0,0,1
337,338,102,2/22/2020,Hokkaido,Japan,1,65.0,2/10/20,2/10/20,NaN,...,0,1,0,0,0,0,0,0,0,0
338,339,103,2/22/2020,Hokkaido,Japan,0,55.0,2/15/2020,2/16/2020,NaN,...,0,0,0,1,0,1,0,0,1,0